[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts"]
ffi=true # Enabling this cheatcode has security implications for your project, as it allows tests to execute arbitrary programs on your computer.

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
